// <auto-generated />
using Carlile_Cookie_Competition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carlile_Cookie_Competition.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008232957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Carlile_Cookie_Competition.Models.Baker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BakerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("baker_name");

                    b.Property<int?>("CookieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cookie_id");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hasVoted");

                    b.HasKey("Id");

                    b.HasIndex("CookieId");

                    b.ToTable("Baker");
                });

            modelBuilder.Entity("Carlile_Cookie_Competition.Models.Cookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BakerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("baker_name");

                    b.Property<string>("CookieName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cookie_name");

                    b.Property<int>("CreativePoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creative_points");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<int>("PresentationPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("presentation_points");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("Cookie");
                });

            modelBuilder.Entity("Carlile_Cookie_Competition.Models.YearRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("ResultsViewable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ResultsViewable");

                    b.Property<int>("YearNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Year");
                });

            modelBuilder.Entity("Carlile_Cookie_Competition.Models.Baker", b =>
                {
                    b.HasOne("Carlile_Cookie_Competition.Models.Cookie", "Cookie")
                        .WithMany("Bakers")
                        .HasForeignKey("CookieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cookie");
                });

            modelBuilder.Entity("Carlile_Cookie_Competition.Models.Cookie", b =>
                {
                    b.Navigation("Bakers");
                });
#pragma warning restore 612, 618
        }
    }
}
